DROP TABLE IF EXISTS engravings CASCADE;

CREATE TABLE engravings (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(10000) NOT NULL,
  image VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL
);